# Generated by Django 4.0.4 on 2022-07-14 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_account_id_alter_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='shop',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=4265089, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='852245', max_length=9),
        ),
    ]
