# Generated by Django 4.0.4 on 2022-07-28 10:11

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_group_id_groupe_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_groupe',
            field=models.CharField(default=authentication.models.generate_groupe_id, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=7607447, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='206557', max_length=9),
        ),
    ]
