# Generated by Django 4.0.4 on 2022-07-28 12:51

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_user_account_id_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id_groupe',
            field=models.CharField(default=authentication.models.generate_groupe_id, max_length=4, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=3361561, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='872833', max_length=9),
        ),
    ]
