# Generated by Django 4.0.4 on 2022-07-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_group_id_groupe_alter_user_account_id_and_more'),
    ]

    operations = [
    ]
