# Generated by Django 4.0.4 on 2022-07-28 14:04

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_merge_20220728_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=authentication.models.generate_transaction_id, max_length=17, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=9827989, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='988887', max_length=9),
        ),
    ]
