# Generated by Django 4.0.4 on 2022-08-04 14:12

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_user_account_id_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=authentication.models.generate_transaction_id, max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=3040209, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='400492', max_length=9),
        ),
    ]
