# Generated by Django 4.0.4 on 2022-08-16 11:23

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_user_wallet_blocked_alter_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_vendues',
            name='code_NFC',
            field=models.CharField(default=authentication.models.generate_wallet_id, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=1891844, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='641366', max_length=9),
        ),
    ]
