# Generated by Django 4.0.4 on 2022-08-16 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_article_vendues_code_nfc_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=7915795, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='256395', max_length=9),
        ),
        migrations.CreateModel(
            name='list_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='authentication.product')),
            ],
        ),
        migrations.AlterField(
            model_name='article_vendues',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.list_articles'),
        ),
    ]
