# Generated by Django 4.0.4 on 2022-08-16 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_list_articles_code_nfc_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_vendues',
            name='code_NFC',
            field=models.CharField(default='', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=6943045, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='214850', max_length=9),
        ),
    ]
