# Generated by Django 4.0.4 on 2022-08-16 13:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_article_vendues_code_nfc_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_vendues',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='article_vendues',
            name='product',
        ),
        migrations.AddField(
            model_name='article_vendues',
            name='product',
            field=models.ManyToManyField(to='authentication.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=4635886, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='923020', max_length=9),
        ),
        migrations.DeleteModel(
            name='list_articles',
        ),
    ]
