# Generated by Django 4.0.4 on 2022-08-16 13:12

import authentication.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_article_vendues_user_remove_article_vendues_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_vendues',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article_vendues',
            name='product',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=7995260, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='485892', max_length=9),
        ),
        migrations.CreateModel(
            name='list_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_NFC', models.CharField(default=authentication.models.generate_wallet_id, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)])),
                ('product', models.ManyToManyField(null=True, to='authentication.product')),
            ],
        ),
        migrations.AddField(
            model_name='article_vendues',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.list_articles'),
        ),
    ]
