# Generated by Django 4.0.4 on 2022-08-16 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_alter_user_account_id_alter_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_vendues',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=4135694, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='448820', max_length=9),
        ),
    ]
