# Generated by Django 4.0.4 on 2022-08-16 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_alter_user_account_id_alter_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_vendues',
            name='product',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=8856834, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='331690', max_length=9),
        ),
    ]
