# Generated by Django 4.0.4 on 2022-08-16 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_article_vendues_product_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=3907175, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='246390', max_length=9),
        ),
        migrations.DeleteModel(
            name='article_vendues',
        ),
    ]
