# Generated by Django 4.0.4 on 2022-08-16 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0049_remove_article_vendues_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_product',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=2491819, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='866595', max_length=9),
        ),
    ]
