# Generated by Django 4.0.4 on 2022-08-18 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0056_alter_product_image_product_alter_shop_image_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionshop',
            name='list_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.list_product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=2521866, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='209405', max_length=9),
        ),
    ]
