# Generated by Django 4.0.4 on 2022-08-19 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0060_remove_transactionshop_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionshop',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.list_product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=1159566, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='883827', max_length=9),
        ),
    ]
