# Generated by Django 4.0.4 on 2022-08-19 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_list_product_timestamp_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=6563127, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='128437', max_length=9),
        ),
    ]
