# Generated by Django 4.0.4 on 2022-08-19 13:50

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_alter_user_account_id_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 13, 50, 58, 861492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=3981478, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='821725', max_length=9),
        ),
    ]
