# Generated by Django 4.0.4 on 2022-08-26 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_alter_user_account_id_alter_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=7410226, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='137590', max_length=9),
        ),
    ]
