# Generated by Django 4.0.4 on 2022-08-28 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_remove_wallet_max_amount_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='max_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=4140362, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='173472', max_length=9),
        ),
    ]
