# Generated by Django 4.0.4 on 2022-08-28 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_wallet_max_amount_alter_user_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='max_amount',
            new_name='maxAmount',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=3018366, max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='428272', max_length=9),
        ),
    ]
